=== r0drigopaes/xmlaw/doc/tese-rodrigo/trafego-aero/simulador/JSIM/jsim/jmessage/koml12.dtd
<?xml version='1.0' encoding='ISO-8859-1'?>

<!-- user hook -->
<!ENTITY % koml.attrGen "">

<!--
  All availables values and objects
-->
<!ENTITY % koml.values
      "(value | object | object-class | array | null | reference | row)*">

<!ENTITY % koml.values.attrG
    "transient  (true|false) 'false'">

<!ENTITY % koml.name
   "name CDATA #IMPLIED">

<!--
  This is a primitive type
-->
<!ENTITY % koml.type "CDATA">

<!--  "(boolean|byte|short|int|long|float|double|char|java.lang.String)">
-->

<!--
  primitive values
-->
<!ELEMENT value (#PCDATA)>
<!ATTLIST value
     %koml.values.attrG;
     %koml.name;
     type %koml.type; #REQUIRED>

<!-- the null object -->
<!ELEMENT null EMPTY>
<!ATTLIST null
      %koml.name;
      %koml.values.attrG;>

<!-- a reference to an object or an array -->
<!ELEMENT reference EMPTY>
<!ATTLIST reference
      %koml.name;
      ref IDREF #REQUIRED>

<!ENTITY % koml.class
    "class CDATA #REQUIRED">

<!ENTITY % koml.id
    "id ID #REQUIRED">

<!ELEMENT super (super?, %koml.values;)>
<!ATTLIST super
    %koml.class;>
   

<!ELEMENT object (super?, %koml.values;)>
<!ATTLIST object
    %koml.values.attrG;
    %koml.name;
    %koml.class;
    %koml.id;>
   
<!ELEMENT object-class (%koml.values;)>
<!ATTLIST object-class
    %koml.values.attrG;   
    %koml.name;
    %koml.class;
    %koml.id;>

<!-- oups, value can be of type String ! -->
<!ELEMENT array  (value | object | array | null | reference)*>
<!ATTLIST array   
    %koml.values.attrG;
    %koml.name;
    %koml.class;
    %koml.id;
    length NMTOKEN "0">
     
<!ELEMENT row (#PCDATA)>
<!ATTLIST row
    size CDATA #REQUIRED>
<!--
    dt:dt CDATA #FIXED "binary.base64"
-->

<!-- class description -->
<!ELEMENT field EMPTY>
<!ATTLIST field
    type %koml.type; #REQUIRED
    %koml.name;>

<!ELEMENT class (field)*>
<!ATTLIST class
    %koml.name;
    uid   CDATA #REQUIRED
    super CDATA "java.lang.Object"
    writemethod (true|false) "false">


<!ELEMENT classes (class)*>
<!ATTLIST classes
   version CDATA #IMPLIED>


<!ELEMENT koml (classes, (array | value | null | object)*)?>
<!ATTLIST koml 
   version CDATA #REQUIRED>

=== r0drigopaes/xmlaw/doc/tese-rodrigo/trafego-aero/simulador/JSIM/jsim/jmessage/mproperties.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE koml SYSTEM "http://www.inria.fr/koala/XML/koml12.dtd">
<koml version='1.21'>
<classes>
<class name='java.lang.Integer' uid='1360826667806852920' super='java.lang.Number'>
<field name='value' type='int'/>
</class>
<class name='jsim.jmessage.ModelProperties' uid='4993936879657733608' super='jsim.jmessage.Message'>
<field name='numOfNodes' type='int'/>
<field name='alpha' type='java.lang.Double[]'/>
<field name='beta' type='java.lang.Double[]'/>
<field name='gamma' type='java.lang.Double[]'/>
<field name='modelName' type='java.lang.String'/>
<field name='nodeName' type='java.lang.String[]'/>
<field name='nodeType' type='int[]'/>
<field name='numOfTokens' type='int[]'/>
<field name='stream' type='java.lang.Integer[]'/>
<field name='timeDist' type='java.lang.String[]'/>
</class>
<class name='java.lang.String[]' uid='-5921575005990323385'>
</class>
<class name='jsim.jmessage.Message' uid='3251745410512505265'>
<field name='actionType' type='java.lang.String'/>
</class>
<class name='java.lang.Number' uid='-8742448824652078965'>
</class>
<class name='java.lang.Integer[]' uid='-101421563860753893'>
</class>
<class name='java.lang.Double' uid='-9172774392245257468' super='java.lang.Number'>
<field name='value' type='double'/>
</class>
<class name='int[]' uid='5600894804908749477'>
</class>
<class name='java.lang.Double[]' uid='-2228528061661948250'>
</class>
</classes>
<object class='jsim.jmessage.ModelProperties' id='i7'>
<super class='jsim.jmessage.Message'>
<value type='java.lang.String' name='actionType'>Inform</value>
</super>
<value type='int' name='numOfNodes'>3</value>
<array class='java.lang.Double[]' id='i10' length='3' name='alpha'>
<object class='java.lang.Double' id='i13'>
<super class='java.lang.Number'>
</super>
<value type='double' name='value'>2000.0</value>
</object>
<object class='java.lang.Double' id='i14'>
<super class='java.lang.Number'>
</super>
<value type='double' name='value'>2000.0</value>
</object>
<object class='java.lang.Double' id='i15'>
<super class='java.lang.Number'>
</super>
<value type='double' name='value'>0.1</value>
</object>
</array>
<array class='java.lang.Double[]' id='i16' length='3' name='beta'>
<object class='java.lang.Double' id='i17'>
<super class='java.lang.Number'>
</super>
<value type='double' name='value'>1000.0</value>
</object>
<object class='java.lang.Double' id='i18'>
<super class='java.lang.Number'>
</super>
<value type='double' name='value'>1000.0</value>
</object>
<null/>
</array>
<array class='java.lang.Double[]' id='i19' length='3' name='gamma'>
<null/>
<null/>
<null/>
</array>
<value type='java.lang.String' name='modelName'>Bank</value>
<array class='java.lang.String[]' id='i22' length='3' name='nodeName'>
<value type='java.lang.String'>Customer</value>
<value type='java.lang.String'>Teller</value>
<value type='java.lang.String'>Exit</value>
</array>
<array class='int[]' id='i27' length='3' name='nodeType'>
<value type='int'>3</value>
<value type='int'>1</value>
<value type='int'>4</value>
</array>
<array class='int[]' id='i28' length='3' name='numOfTokens'>
<value type='int'>100</value>
<value type='int'>1</value>
<value type='int'>0</value>
</array>
<array class='java.lang.Integer[]' id='i30' length='3' name='stream'>
<object class='java.lang.Integer' id='i32'>
<super class='java.lang.Number'>
</super>
<value type='int' name='value'>0</value>
</object>
<object class='java.lang.Integer' id='i33'>
<super class='java.lang.Number'>
</super>
<value type='int' name='value'>0</value>
</object>
<object class='java.lang.Integer' id='i34'>
<super class='java.lang.Number'>
</super>
<value type='int' name='value'>0</value>
</object>
</array>
<array class='java.lang.String[]' id='i35' length='3' name='timeDist'>
<value type='java.lang.String'>Uniform</value>
<value type='java.lang.String'>Uniform</value>
<value type='java.lang.String'>Bernoulli</value>
</array>
</object>
</koml>

=== r0drigopaes/xmlaw/doc/tese-rodrigo/trafego-aero/simulador/JSIM/jsim/jmessage/simulate.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE koml SYSTEM "http://www.inria.fr/koala/XML/koml12.dtd">
<koml version='1.21'>
<classes>
<class name='java.lang.Double' uid='-9172774392245257468' super='java.lang.Number'>
<field name='value' type='double'/>
</class>
<class name='java.lang.Number' uid='-8742448824652078965'>
</class>
<class name='jsim.jmessage.Simulate' uid='675650800527491650' super='jsim.jmessage.Message'>
<field name='agentName' type='java.lang.String'/>
<field name='batchSize' type='java.lang.Integer'/>
<field name='confidenceLevel' type='java.lang.Double'/>
<field name='numOfBatches' type='java.lang.Integer'/>
<field name='numOfReplications' type='java.lang.Integer'/>
<field name='relativePrecision' type='java.lang.Double'/>
<field name='replicationSize' type='java.lang.Integer'/>
<field name='transientPeriod' type='java.lang.Double'/>
</class>
<class name='jsim.jmessage.Message' uid='3251745410512505265'>
<field name='actionType' type='java.lang.String'/>
</class>
<class name='java.lang.Integer' uid='1360826667806852920' super='java.lang.Number'>
<field name='value' type='int'/>
</class>
</classes>
<object class='jsim.jmessage.Simulate' id='i5'>
<super class='jsim.jmessage.Message'>
<value type='java.lang.String' name='actionType'>start</value>
</super>
<value type='java.lang.String' name='agentName'>BatchMeansAgent</value>
<object class='java.lang.Integer' id='i10' name='batchSize'>
<super class='java.lang.Number'>
</super>
<value type='int' name='value'>4</value>
</object>
<object class='java.lang.Double' id='i12' name='confidenceLevel'>
<super class='java.lang.Number'>
</super>
<value type='double' name='value'>0.95</value>
</object>
<object class='java.lang.Integer' id='i13' name='numOfBatches'>
<super class='java.lang.Number'>
</super>
<value type='int' name='value'>8</value>
</object>
<null name='numOfReplications'/>
<object class='java.lang.Double' id='i14' name='relativePrecision'>
<super class='java.lang.Number'>
</super>
<value type='double' name='value'>0.1</value>
</object>
<null name='replicationSize'/>
<null name='transientPeriod'/>
</object>
</koml>

=== r0drigopaes/xmlaw/doc/tese-rodrigo/trafego-aero/simulador/JSIM/jsim/jmessage/query.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE koml SYSTEM "http://www.inria.fr/koala/XML/koml12.dtd">
<koml version='1.21'>
<classes>
<class name='jsim.jmessage.Query' uid='-5798279705999435565' super='jsim.jmessage.Message'>
<field name='queryStr' type='java.lang.String'/>
</class>
<class name='jsim.jmessage.DBConnectionInfo' uid='-4436913034187897049'>
<field name='driverClassName' type='java.lang.String'/>
<field name='framework' type='java.lang.String'/>
<field name='passwd' type='java.lang.String'/>
<field name='url' type='java.lang.String'/>
<field name='username' type='java.lang.String'/>
</class>
<class name='jsim.jmessage.Message' uid='3251745410512505265'>
<field name='actionType' type='java.lang.String'/>
</class>
</classes>
<object class='jsim.jmessage.Query' id='i3'>
<super class='jsim.jmessage.Message'>
<value type='java.lang.String' name='actionType'>Sequence query</value>
</super>
<value type='java.lang.String' name='queryStr'>SELECT seq FROM sequence</value>
</object>
<object class='jsim.jmessage.DBConnectionInfo' id='i7'>
<value type='java.lang.String' name='driverClassName'>COM.cloudscape.core.RmiJdbcDriver</value>
<value type='java.lang.String' name='framework'>rmijdbc</value>
<value type='java.lang.String' name='passwd'></value>
<value type='java.lang.String' name='url'>jdbc:cloudscape:rmi://chief.cs.uga.edu:2001/JsimDB</value>
<null name='username'/>
</object>
</koml>

=== r0drigopaes/xmlaw/doc/tese-rodrigo/trafego-aero/simulador/JSIM/jsim/jmessage/instruct.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE koml SYSTEM "http://www.inria.fr/koala/XML/koml12.dtd">
<koml version='1.21'>
<classes>
<class name='jsim.jmessage.Message' uid='3251745410512505265'>
<field name='actionType' type='java.lang.String'/>
</class>
<class name='jsim.jmessage.Instruct' uid='2749693026728532532' super='jsim.jmessage.Message'>
<field name='scenarioID' type='java.lang.Integer'/>
</class>
<class name='java.lang.Integer' uid='1360826667806852920' super='java.lang.Number'>
<field name='value' type='int'/>
</class>
<class name='java.lang.Number' uid='-8742448824652078965'>
</class>
</classes>
<object class='jsim.jmessage.Instruct' id='i4'>
<super class='jsim.jmessage.Message'>
<value type='java.lang.String' name='actionType'>Instruct</value>
</super>
<object class='java.lang.Integer' id='i8' name='scenarioID'>
<super class='java.lang.Number'>
</super>
<value type='int' name='value'>11</value>
</object>
</object>
</koml>
